version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production

    command: node index.js
    volumes:
      - ./:/app
      - /app/node_modules
