name: Docker Image CI

on:
  push:
  pull_request:

jobs:
  #   build:
  #     runs-on: ubuntu-latest

  #     steps:
  #       - uses: actions/checkout@v2

  #       - name: Run docker-compose. Build the Docker image
  #         run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
  #       # - name: Build the Docker image
  #       # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1

      - name: Install packages
        run: |
          npm install

      - name: Run docker-compose. Build the Docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

      - name: Start server and run tests
        run: |
          npm start & npx wait-on http://localhost:3000
          ./k6 run tests/sampleCSVTest.js

      # - name: Run sampleCSV test
      #   run: wait-on http://localhost:3000
      #     ./k6 run tests/sampleCSVTest.js

      - name: Run notCSV test
        run: ./k6 run tests/notCSVTest.js

      - name: Run emptyRequest test
        run: ./k6 run tests/emptyRequestTest.js

      - name: Run load test
        run: ./k6 run tests/loadTest.js
