name: Docker Image CI

on:
  push: [main]
  pull_request: [main]

jobs:
  #   build:
  #     runs-on: ubuntu-latest

  #     steps:
  #       - uses: actions/checkout@v2

  #       - name: Run docker-compose. Build the Docker image
  #         run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
  #       # - name: Build the Docker image
  #       # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1

      - name: Install packages
        run: |
          npm install

      - name: Run docker-compose. Build the Docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

      - name: Install newman
        run: npm install -g newman

      - name: Run tests
        run: newman run "tests/Hestia-api Tests.postman_collection.json"
