name: Docker Image CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run docker-compose. Build the Docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
      # - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
